# Generated by Django 3.2.20 on 2023-07-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230717_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Comment',
            new_name='comment',
        ),
    ]
