# Generated by Django 3.2.20 on 2023-07-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20230719_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_images/'),
        ),
    ]
