# Generated by Django 3.2.20 on 2023-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20230720_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thumbnail_image',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_images/'),
        ),
    ]
