# Generated by Django 3.2.20 on 2023-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user_images/'),
            preserve_default=False,
        ),
    ]
